<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.1 (Python 3.12.3 on win32)" generated="2024-10-12T19:00:03.953020" rpa="false" schemaversion="5">
<suite id="s1" name="TC001" source="C:\Users\chiya\PycharmProjects\RPS_RobotFramework\Test\UI\TC001.robot">
<test id="s1-t1" name="TC001" line="5">
<kw name="open chrome">
<msg time="2024-10-12T19:00:03.984263" level="FAIL">No keyword with name 'open chrome' found.</msg>
<status status="FAIL" start="2024-10-12T19:00:03.984263" elapsed="0.000000">No keyword with name 'open chrome' found.</status>
</kw>
<status status="FAIL" start="2024-10-12T19:00:03.984263" elapsed="0.000000">No keyword with name 'open chrome' found.</status>
</test>
<status status="FAIL" start="2024-10-12T19:00:03.953020" elapsed="0.031243"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="TC001">TC001</stat>
</suite>
</statistics>
<errors>
<msg time="2024-10-12T19:00:03.984263" level="ERROR">Error in file 'C:\Users\chiya\PycharmProjects\RPS_RobotFramework\Test\UI\TC001.robot' on line 2: Resource file '\Resources\Resource.robot' does not exist.</msg>
</errors>
</robot>
